'use client';
import { useEffect, useState } from 'react';
import { AdminIcon } from './admin-icons';
type Capability = { capability: string; state: string; score: number; qualityScore: number; reasons: string[] };
type Baseline = { state: string; confidence: string; observedWeeks: number; serviceEvidenceWeeks: number; travelEvidenceWeeks: number; service: { completedVisits: { median: number | null; p75: number | null; p90: number | null } }; reasons: string[] };
type Pressure = 'WITHIN_BASELINE' | 'ABOVE_P75' | 'ABOVE_P90' | 'UNKNOWN';
type Risk = { state: string; severity: 'UNKNOWN' | 'LOW' | 'MEDIUM' | 'HIGH'; confidence: string; reasons: string[]; signals: Array<{ code: string; severity: string }> };
type TechnicianRow = { id: string; name: string; username: string; baseline: Baseline; workload: { standardCurrent: number; standardCarryover: number; smartcleanCurrent: number; smartcleanCarryover: number; equipmentKnownPointCount: number; equipmentUnknownPointCount: number; assignedLocatedPointCount: number; assignedUnlocatedPointCount: number; assignedFieldP90RadiusMeters: number | null; assignedRouteEstimateMeters: number | null }; assessment: { evidenceState: string; baselineState: string; baselineConfidence: string; servicePressure: { coolerCount: Pressure; towerCount: Pressure; tapCount: Pressure; smarttapCount: Pressure }; travelPressure: { routeDistanceMeters: Pressure; fieldP90RadiusMeters: Pressure }; reasons: string[] }; risk: Risk };
type Difficulty = { pointId: string; state: string; confidence: string; score: number | null; equipmentProfileComplete: boolean; equipmentProfile: { confidence: string; confidenceScore: number; stability: string; verificationAgeDays: number | null; anomalyCodes: string[] }; risk: Risk; location: { state: string; confidenceScore: number; confidence: string; contradictionCount: number; reasonCodes: string[] } | null; geography: { located: boolean; isolated: boolean; nearestNeighborMeters: number | null }; history: { visits: number; attempts: number; missed: number; completed: number }; reasons: string[]; point: { code: string; name: string; region: { name: string } | null } | null };
type Planning = { state: string; reasons: string[]; recommendations: Array<{ id: string; type: string; technicianId: string; priority: number; severity: string; confidence: string; reasonCodes: string[]; constraints: string[] }> };
type SimilarWeek = { weekKey: string; similarity: number; confidence: string; dimensionsUsed: number; reasons: string[] };
type DataQuality = { score: number; confidence: string; reasonCodes: string[]; issues: Array<{ code: string; severity: string; priority: number; entityId: string; evidence: Record<string, string | number | boolean | null> }> };
type Backtest = { state: string; evaluatedPredictions: number; skippedPredictions: number; truePositive: number; falsePositive: number; trueNegative: number; falseNegative: number; precision: number | null; recall: number | null; accuracy: number | null; reasonCodes: string[] };
type RegionHealth = { regionId: string; score: number; state: 'GREEN' | 'AMBER' | 'RED'; confidence: string; trend: string; reasonCodes: string[]; evidence: Record<string, string | number | boolean | null> };
type Dashboard = { weeks: number; currentWeek: string | null; generatedAt: string; engineVersion: string; featureSchemaVersion: string; planning: Planning; backtest: Backtest; regionHealth: RegionHealth[]; dataQuality: DataQuality; similarWeeks: SimilarWeek[]; maturity: { overallState: string; overallScore: number; evidence: { weeks: number; visits: number; attempts: number; activePoints: number; locatedPoints: number; locationCoverage: number; equipmentProfileCoverage: number }; capabilities: Capability[] }; unassigned: { standardCurrent: number; standardCarryover: number; smartcleanCurrent: number; smartcleanCarryover: number }; technicians: TechnicianRow[]; pointDifficulty: Difficulty[] };
const stateLabel = (value: string) => ({ INACTIVE: 'Pasif', WARMING_UP: 'Isınıyor', ACTIVE: 'Aktif', RELIABLE: 'Güvenilir', READY: 'Hazır', INSUFFICIENT_DATA: 'Veri yetersiz' }[value] ?? value);
const pressureLabel = (value: Pressure) => ({ WITHIN_BASELINE: 'Normal', ABOVE_P75: 'Yüksek', ABOVE_P90: 'Çok yüksek', UNKNOWN: 'Bilinmiyor' }[value]);
const pressureRank: Record<Pressure, number> = { UNKNOWN: -1, WITHIN_BASELINE: 0, ABOVE_P75: 1, ABOVE_P90: 2 };
const worstPressure = (values: Pressure[]) => values.reduce<Pressure>((worst, value) => pressureRank[value] > pressureRank[worst] ? value : worst, 'UNKNOWN');
const riskLabel = (value: Risk['severity']) => ({ UNKNOWN: 'Bilinmiyor', LOW: 'Düşük', MEDIUM: 'Orta', HIGH: 'Yüksek' }[value]);
export default function AiDashboard() {
const [data, setData] = useState<Dashboard | null>(null);
const [busy, setBusy] = useState(false);
const [error, setError] = useState('');
async function load() {
setBusy(true); setError('');
try {
const response = await fetch('/api/backend/ai/admin-dashboard?weeks=12');
const body = await response.json().catch(() => null);
if (!response.ok) throw new Error(Array.isArray(body?.message) ? body.message.join(', ') : body?.message || `HTTP ${response.status}`);
setData(body as Dashboard);
} catch (e) { setError(e instanceof Error ? e.message : String(e)); }
finally { setBusy(false); }
}
useEffect(() => { void load(); }, []);
if (!data) return <section className="panel"><div className="panelHeader"><div><h2>Sanal İstatistikçi</h2><p>AI analizleri hazırlanıyor.</p></div></div>{error ? <div className="error banner">{error}</div> : <div className="emptyState"><AdminIcon name={busy ? 'clock' : 'analytics'} /><strong>{busy ? 'Analiz hazırlanıyor' : 'Analiz verisi yok'}</strong><span>{busy ? 'Son haftaların saha verileri işleniyor.' : 'Yeterli veri oluştuğunda burada görünecek.'}</span></div>}</section>;
const currentUnassigned = data.unassigned.standardCurrent + data.unassigned.smartcleanCurrent;
return <>
<section className="stats"><div className="stat"><strong>{data.maturity.overallScore}</strong><span>AI olgunluk skoru</span></div><div className="stat"><strong>{data.dataQuality.score}</strong><span>Veri kalite skoru</span></div><div className="stat"><strong>{stateLabel(data.maturity.overallState)}</strong><span>Genel durum</span></div><div className="stat"><strong>{Math.round(data.maturity.evidence.locationCoverage * 100)}%</strong><span>Konum kapsaması</span></div><div className="stat"><strong>{Math.round(data.maturity.evidence.equipmentProfileCoverage * 100)}%</strong><span>Ekipman kapsaması</span></div><div className="stat"><strong>{currentUnassigned}</strong><span>Atanmamış mevcut iş</span></div></section>
<section className="panel"><div className="panelHeader"><div><h2>Sanal İstatistikçi</h2><p>Son {data.weeks} haftalık veriden üretilen kapasite, risk ve veri olgunluğu görünümü. · {data.engineVersion}</p></div><button className="ghost iconAction" onClick={() => void load()} disabled={busy}><AdminIcon name="refresh" size={17} /><span>YENİLE</span></button></div>{error ? <div className="error banner">{error}</div> : null}<div className="tableWrap"><table><thead><tr><th>Yetenek</th><th>Durum</th><th>Skor</th><th>Veri kalitesi</th><th>Açıklama</th></tr></thead><tbody>{data.maturity.capabilities.map((item) => <tr key={item.capability}><td><strong>{item.capability}</strong></td><td><span className={item.state === 'ACTIVE' || item.state === 'RELIABLE' ? 'pill active' : 'pill'}>{stateLabel(item.state)}</span></td><td>{item.score}</td><td>{item.qualityScore}</td><td className="muted">{item.reasons.join(' · ')}</td></tr>)}</tbody></table></div></section>
<section className="panel"><div className="panelHeader"><div><h2>Teknisyen Kapasitesi</h2><p>Mevcut iş yükü ile öğrenilmiş haftalık baseline karşılaştırması.</p></div></div><div className="tableWrap"><table><thead><tr><th>Teknisyen</th><th>Baseline</th><th>Mevcut iş</th><th>Devreden</th><th>Ekipman verisi</th><th>Servis baskısı</th><th>Coğrafi baskı</th><th>Rota baskısı</th><th>Risk</th><th>Medyan tamamlanan</th></tr></thead><tbody>{data.technicians.map((item) => { const current = item.workload.standardCurrent + item.workload.smartcleanCurrent; const carry = item.workload.standardCarryover + item.workload.smartcleanCarryover; const servicePressure = worstPressure(Object.values(item.assessment.servicePressure)); const geoPressure = item.assessment.travelPressure.fieldP90RadiusMeters; return <tr key={item.id}><td><strong>{item.name}</strong><div className="muted">@{item.username}</div></td><td><span className={item.baseline.state === 'ACTIVE' ? 'pill active' : 'pill'}>{stateLabel(item.baseline.state)} / {item.baseline.confidence}</span><div className="muted">{item.baseline.observedWeeks} hafta gözlem</div></td><td>{current}</td><td>{carry}</td><td>{item.workload.equipmentKnownPointCount} bilinen / {item.workload.equipmentUnknownPointCount} eksik<div className="muted">Konum: {item.workload.assignedLocatedPointCount} / {item.workload.assignedUnlocatedPointCount} eksik</div></td><td><span className={servicePressure === 'WITHIN_BASELINE' ? 'pill active' : 'pill'}>{pressureLabel(servicePressure)}</span></td><td><span className={geoPressure === 'WITHIN_BASELINE' ? 'pill active' : 'pill'}>{pressureLabel(geoPressure)}</span><div className="muted">{item.workload.assignedFieldP90RadiusMeters === null ? '—' : `${Math.round(item.workload.assignedFieldP90RadiusMeters / 100) / 10} km P90`}</div></td><td><span className={item.assessment.travelPressure.routeDistanceMeters === 'WITHIN_BASELINE' ? 'pill active' : 'pill'}>{pressureLabel(item.assessment.travelPressure.routeDistanceMeters)}</span><div className="muted">{item.workload.assignedRouteEstimateMeters === null ? '—' : `${Math.round(item.workload.assignedRouteEstimateMeters / 100) / 10} km tahmini rota`}</div></td><td><span className={item.risk.severity === 'LOW' ? 'pill active' : 'pill'}>{riskLabel(item.risk.severity)}</span><div className="muted">{item.risk.signals.map((signal) => signal.code).join(' · ') || item.risk.reasons.join(' · ') || 'Risk sinyali yok'}</div></td><td>{item.baseline.service.completedVisits.median ?? '—'}<div className="muted">{item.assessment.reasons.join(' · ') || 'Veri yeterli'}</div></td></tr>; })}</tbody></table></div></section>

<section className="panel"><div className="panelHeader"><div><h2>Bölge Sağlığı</h2><p>Konum kapsaması, başarısız deneme oranı, SmartClean devri ve rota parçalanması birlikte izlenir.</p></div></div>{data.regionHealth.length ? <div className="tableWrap"><table><thead><tr><th>Bölge</th><th>Skor</th><th>Durum</th><th>Trend</th><th>Güven</th><th>Neden</th></tr></thead><tbody>{data.regionHealth.map((item) => <tr key={item.regionId}><td><strong>{item.regionId}</strong></td><td>{item.score}</td><td><span className={item.state === 'GREEN' ? 'pill active' : 'pill'}>{item.state}</span></td><td>{item.trend}</td><td>{item.confidence}</td><td className="muted">{item.reasonCodes.join(' · ')}</td></tr>)}</tbody></table></div> : <p className="muted">Bölge sağlık verisi yok.</p>}</section>
<section className="panel"><div className="panelHeader"><div><h2>Geçmiş Risk Backtest</h2><p>Bir haftada üretilen nokta riskleri bir sonraki haftadaki gerçek deneme/missed sonuçlarıyla karşılaştırılır.</p></div></div><div className="stats"><div className="stat"><strong>{data.backtest.evaluatedPredictions}</strong><span>Değerlendirilen tahmin</span></div><div className="stat"><strong>{data.backtest.precision === null ? '—' : `${Math.round(data.backtest.precision * 100)}%`}</strong><span>Precision</span></div><div className="stat"><strong>{data.backtest.recall === null ? '—' : `${Math.round(data.backtest.recall * 100)}%`}</strong><span>Recall</span></div><div className="stat"><strong>{data.backtest.accuracy === null ? '—' : `${Math.round(data.backtest.accuracy * 100)}%`}</strong><span>Accuracy</span></div></div><p className="muted">TP {data.backtest.truePositive} · FP {data.backtest.falsePositive} · TN {data.backtest.trueNegative} · FN {data.backtest.falseNegative} · Atlanan {data.backtest.skippedPredictions}{data.backtest.reasonCodes.length ? ` · ${data.backtest.reasonCodes.join(' · ')}` : ''}</p></section>
<section className="panel"><div className="panelHeader"><div><h2>Veri Kalitesi Öncelik Kuyruğu</h2><p>AI kararlarını bozabilecek eksik, eski veya çelişkili kayıtlar en yüksek öncelikten başlanarak listelenir.</p></div></div>{data.dataQuality.issues.length ? <div className="tableWrap"><table><thead><tr><th>Öncelik</th><th>Seviye</th><th>Nokta</th><th>Sorun</th><th>Kanıt</th></tr></thead><tbody>{data.dataQuality.issues.slice(0, 40).map((item, index) => { const point = data.pointDifficulty.find((p) => p.pointId === item.entityId)?.point; return <tr key={`${item.entityId}-${item.code}-${index}`}><td><strong>{item.priority}</strong></td><td>{item.severity}</td><td>{point?.name ?? item.entityId}<div className="muted">{point?.code ?? '—'}</div></td><td>{item.code}</td><td className="muted">{Object.entries(item.evidence).map(([k,v]) => `${k}=${String(v)}`).join(' · ') || '—'}</td></tr>; })}</tbody></table></div> : <div className="emptyState"><AdminIcon name="analytics" /><strong>Kritik veri kalite sorunu yok</strong><span>Mevcut snapshot için öncelikli düzeltme kuyruğu boş.</span></div>}</section>
<section className="panel"><div className="panelHeader"><div><h2>Benzer Haftalar</h2><p>Ekipman karması, iş yükü ve coğrafi dağılım birlikte karşılaştırılır.</p></div></div>{data.similarWeeks.length ? <div className="tableWrap"><table><thead><tr><th>Hafta</th><th>Benzerlik</th><th>Güven</th><th>Boyut</th><th>Neden</th></tr></thead><tbody>{data.similarWeeks.map((item) => <tr key={item.weekKey}><td><strong>{item.weekKey}</strong></td><td>{item.similarity}%</td><td>{item.confidence}</td><td>{item.dimensionsUsed}</td><td className="muted">{item.reasons.join(' · ')}</td></tr>)}</tbody></table></div> : <p className="muted">Karşılaştırılabilir geçmiş hafta yok.</p>}</section>
<section className="panel"><div className="panelHeader"><div><h2>AI Planlama Önerileri</h2><p>Operasyon değişikliği yapmaz; mevcut iş kuralları korunarak öncelikli inceleme önerileri üretir.</p></div></div>{data.planning.recommendations.length ? <div className="tableWrap"><table><thead><tr><th>Öncelik</th><th>Öneri</th><th>Teknisyen</th><th>Risk / Güven</th><th>Neden</th></tr></thead><tbody>{data.planning.recommendations.slice(0, 30).map((item) => { const technician = data.technicians.find((t) => t.id === item.technicianId); return <tr key={item.id}><td><strong>{item.priority}</strong></td><td>{item.type}</td><td>{technician?.name ?? item.technicianId}</td><td>{item.severity} / {item.confidence}</td><td className="muted">{item.reasonCodes.join(' · ') || '—'}<div>{item.constraints.join(' · ')}</div></td></tr>; })}</tbody></table></div> : <div className="emptyState"><AdminIcon name="analytics" /><strong>{data.planning.state === 'READY' ? 'Planlama önerisi yok' : 'Planlama için veri yetersiz'}</strong><span>{data.planning.reasons.join(' · ') || 'Mevcut iş yükünde ek müdahale önerisi üretilmedi.'}</span></div>}</section>

<section className="panel"><div className="panelHeader"><div><h2>Nokta Zorluk Profili</h2><p>Aktif skorlar üstte; veri yetersiz noktalar warming-up olarak ayrıca görünür.</p></div></div><div className="tableWrap"><table><thead><tr><th>Nokta</th><th>Skor</th><th>Durum</th><th>Ekipman güveni</th><th>Risk</th><th>Ziyaret / Deneme</th><th>Konum</th><th>Konum güveni</th><th>Neden</th></tr></thead><tbody>{data.pointDifficulty.slice(0, 40).map((item) => <tr key={item.pointId}><td><strong>{item.point?.name ?? item.pointId}</strong><div className="muted">{item.point?.code ?? '—'} · {item.point?.region?.name ?? 'Bölge yok'}</div></td><td>{item.score ?? '—'}</td><td><span className={item.state === 'ACTIVE' ? 'pill active' : 'pill'}>{stateLabel(item.state)} / {item.confidence}</span></td><td><strong>{item.equipmentProfile.confidence}</strong><div className="muted">{item.equipmentProfile.confidenceScore}/100 · {item.equipmentProfile.stability}{item.equipmentProfile.anomalyCodes.length ? ` · ${item.equipmentProfile.anomalyCodes.join(' · ')}` : ''}</div></td><td><span className={item.risk.severity === 'LOW' ? 'pill active' : 'pill'}>{riskLabel(item.risk.severity)}</span><div className="muted">{item.risk.signals.map((signal) => signal.code).join(' · ') || item.risk.reasons.join(' · ') || 'Risk sinyali yok'}</div></td><td>{item.history.visits} / {item.history.attempts}</td><td>{item.geography.located ? item.geography.isolated ? 'İzole' : 'Konumlu' : 'Eksik'}</td><td><strong>{item.location?.confidenceScore ?? 0}/100</strong><div className="muted">{item.location?.state ?? 'UNKNOWN'}{item.location?.contradictionCount ? ` · ${item.location.contradictionCount} çelişki` : ''}</div></td><td className="muted">{item.reasons.join(' · ') || item.location?.reasonCodes.join(' · ') || 'Yeterli veri'}</td></tr>)}</tbody></table></div></section>
</>;
}
