'use client';

import { useEffect, useMemo, useState } from 'react';

type Point = { id: string; code: string; name: string; status: 'ACTIVE' | 'PASSIVE' | 'CANCELLED'; maintenanceType: 'STANDARD' | 'SMARTCLEAN'; maintenanceWeek?: number | null; region?: { id: string; name: string } | null };
type Region = { id: string; name: string };
type Action = 'SET_REGION' | 'SET_STATUS' | 'SET_STANDARD_WEEK' | 'SET_SMARTCLEAN';

export default function BulkOperations() {
  const [points, setPoints] = useState<Point[]>([]); const [regions, setRegions] = useState<Region[]>([]); const [selected, setSelected] = useState<string[]>([]); const [action, setAction] = useState<Action>('SET_REGION'); const [regionId, setRegionId] = useState(''); const [status, setStatus] = useState<Point['status']>('ACTIVE'); const [week, setWeek] = useState('1'); const [reference, setReference] = useState(''); const [preview, setPreview] = useState(false); const [confirmed, setConfirmed] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { void Promise.all([fetch('/api/backend/points').then((r) => r.json()), fetch('/api/backend/regions').then((r) => r.json())]).then(([pointList, regionList]) => { setPoints(pointList); setRegions(regionList); setRegionId(regionList[0]?.id ?? ''); }); }, []);
  const chosen = useMemo(() => points.filter((point) => selected.includes(point.id)), [points, selected]);
  const target = action === 'SET_REGION' ? regions.find((region) => region.id === regionId)?.name : action === 'SET_STATUS' ? status : action === 'SET_STANDARD_WEEK' ? `Hafta ${week}` : `SmartClean / ${reference || 'referans tarihi eksik'}`;
  function toggle(id: string) { setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); setPreview(false); setConfirmed(false); }
  async function apply() { if (!confirmed || !selected.length) return; const payload: Record<string, unknown> = { pointIds: selected, action }; if (action === 'SET_REGION') payload.regionId = regionId; if (action === 'SET_STATUS') payload.status = status; if (action === 'SET_STANDARD_WEEK') payload.maintenanceWeek = Number(week); if (action === 'SET_SMARTCLEAN') { payload.maintenanceWeek = Number(week); payload.smartcleanReferenceAt = reference; } setBusy(true); try { const response = await fetch('/api/backend/points/bulk-update', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(`HTTP ${response.status}`); setMessage(`${selected.length} nokta için işlem tamamlandı.`); setSelected([]); setPreview(false); setConfirmed(false); } catch (cause) { setMessage(cause instanceof Error ? cause.message : String(cause)); } finally { setBusy(false); } }
  return <section className="panel"><div className="panelHeader"><div><h2>Toplu İşlemler</h2><p>Birden fazla noktayı önizleme ve açık onay ile güncelleyin.</p></div><strong>{selected.length} nokta seçildi</strong></div>{message ? <div className="banner">{message}</div> : null}<div className="filterBar"><select value={action} onChange={(event) => { setAction(event.target.value as Action); setPreview(false); setConfirmed(false); }}><option value="SET_REGION">Bölge değiştir</option><option value="SET_STATUS">Durum değiştir</option><option value="SET_STANDARD_WEEK">STANDARD rut haftası değiştir</option><option value="SET_SMARTCLEAN">SmartClean ayarla</option></select>{action === 'SET_REGION' ? <select value={regionId} onChange={(event) => setRegionId(event.target.value)}>{regions.map((region) => <option key={region.id} value={region.id}>{region.name}</option>)}</select> : action === 'SET_STATUS' ? <select value={status} onChange={(event) => setStatus(event.target.value as Point['status'])}><option value="ACTIVE">Aktif</option><option value="PASSIVE">Pasif</option><option value="CANCELLED">İptal</option></select> : <><select value={week} onChange={(event) => setWeek(event.target.value)}><option value="1">Hafta 1</option><option value="2">Hafta 2</option></select>{action === 'SET_SMARTCLEAN' ? <input type="date" value={reference} onChange={(event) => setReference(event.target.value)} /> : null}</>}<button disabled={!selected.length} onClick={() => setPreview(true)}>Değişiklikleri Önizle</button></div><div className="tableWrap"><table><thead><tr><th>Seç</th><th>Kod</th><th>Nokta</th><th>Mevcut Bölge</th><th>Durum</th></tr></thead><tbody>{points.map((point) => <tr key={point.id}><td><input type="checkbox" checked={selected.includes(point.id)} onChange={() => toggle(point.id)} /></td><td>{point.code}</td><td>{point.name}</td><td>{point.region?.name ?? '—'}</td><td>{point.status}</td></tr>)}</tbody></table></div>{preview ? <section className="panel priorityPanel"><h2>Değişiklik Önizlemesi</h2><p>{chosen.length} nokta için yeni değer: <strong>{target}</strong>.</p>{action === 'SET_REGION' ? <div className="banner">Bölge değişikliği yalnız organizasyon bilgisidir; mevcut konum verileri korunur ve yeniden konum araması çalışmaz.</div> : null}<label className="helpOption"><input type="checkbox" checked={confirmed} onChange={(event) => setConfirmed(event.target.checked)} /><span><strong>Etkilenecek kayıtları ve yeni değeri kontrol ettim.</strong><small>İşlem audit altyapısında kayıtlı kalır.</small></span></label><button disabled={!confirmed || busy || (action === 'SET_SMARTCLEAN' && !reference)} onClick={() => void apply()}>Uygulamayı Onayla</button></section> : null}</section>;
}
